// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/grpc/proto/velocity/v1/velocity.proto

package velocityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VelocityService_CreateUser_FullMethodName = "/velocity.v1.VelocityService/CreateUser"
)

// VelocityServiceClient is the client API for VelocityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VelocityServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type velocityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVelocityServiceClient(cc grpc.ClientConnInterface) VelocityServiceClient {
	return &velocityServiceClient{cc}
}

func (c *velocityServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, VelocityService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VelocityServiceServer is the server API for VelocityService service.
// All implementations must embed UnimplementedVelocityServiceServer
// for forward compatibility.
type VelocityServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedVelocityServiceServer()
}

// UnimplementedVelocityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVelocityServiceServer struct{}

func (UnimplementedVelocityServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedVelocityServiceServer) mustEmbedUnimplementedVelocityServiceServer() {}
func (UnimplementedVelocityServiceServer) testEmbeddedByValue()                         {}

// UnsafeVelocityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VelocityServiceServer will
// result in compilation errors.
type UnsafeVelocityServiceServer interface {
	mustEmbedUnimplementedVelocityServiceServer()
}

func RegisterVelocityServiceServer(s grpc.ServiceRegistrar, srv VelocityServiceServer) {
	// If the following call panics, it indicates UnimplementedVelocityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VelocityService_ServiceDesc, srv)
}

func _VelocityService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VelocityServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VelocityService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VelocityServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VelocityService_ServiceDesc is the grpc.ServiceDesc for VelocityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VelocityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velocity.v1.VelocityService",
	HandlerType: (*VelocityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _VelocityService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/velocity/v1/velocity.proto",
}
