// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/proto/velocity/v1/velocity.proto

package velocityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_internal_grpc_proto_velocity_v1_velocity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_velocity_v1_velocity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_internal_grpc_proto_velocity_v1_velocity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_velocity_v1_velocity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_internal_grpc_proto_velocity_v1_velocity_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_velocity_v1_velocity_proto_rawDesc = "" +
	"\n" +
	".internal/grpc/proto/velocity/v1/velocity.proto\x12\vvelocity.v1\"9\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"s\n" +
	"\x12CreateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email2`\n" +
	"\x0fVelocityService\x12M\n" +
	"\n" +
	"CreateUser\x12\x1e.velocity.v1.CreateUserRequest\x1a\x1f.velocity.v1.CreateUserResponseB?Z=velocity/internal/transport/grpc/proto/velocity/v1;velocityv1b\x06proto3"

var (
	file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescData []byte
)

func file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_velocity_v1_velocity_proto_rawDesc), len(file_internal_grpc_proto_velocity_v1_velocity_proto_rawDesc)))
	})
	return file_internal_grpc_proto_velocity_v1_velocity_proto_rawDescData
}

var file_internal_grpc_proto_velocity_v1_velocity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_proto_velocity_v1_velocity_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: velocity.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: velocity.v1.CreateUserResponse
}
var file_internal_grpc_proto_velocity_v1_velocity_proto_depIdxs = []int32{
	0, // 0: velocity.v1.VelocityService.CreateUser:input_type -> velocity.v1.CreateUserRequest
	1, // 1: velocity.v1.VelocityService.CreateUser:output_type -> velocity.v1.CreateUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_velocity_v1_velocity_proto_init() }
func file_internal_grpc_proto_velocity_v1_velocity_proto_init() {
	if File_internal_grpc_proto_velocity_v1_velocity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_velocity_v1_velocity_proto_rawDesc), len(file_internal_grpc_proto_velocity_v1_velocity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_velocity_v1_velocity_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_velocity_v1_velocity_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_velocity_v1_velocity_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_velocity_v1_velocity_proto = out.File
	file_internal_grpc_proto_velocity_v1_velocity_proto_goTypes = nil
	file_internal_grpc_proto_velocity_v1_velocity_proto_depIdxs = nil
}
